/** Assemble evidence from completed tests; refuse stale or failed browser runs. */
import {readFile,writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const root=new URL('../',import.meta.url),read=p=>readFile(new URL(p,root),'utf8');
const build=JSON.parse(await read('dist/build-info.json')),hash=createHash('sha256').update(await read('STRATA-Offline.html')).digest('hex');
if(hash!==build.offlineSHA256)throw Error('Standalone does not match build-info. Rebuild and retest.');
const suites={};
for(const name of ['core','features','layout','studio']){
 const r=JSON.parse(await read('artifacts/browser-'+name+'.json'));
 if(r.standaloneSHA256!==hash)throw Error(`Stale ${name} browser evidence: rerun that suite on this build.`);
 if(r.failed||r.pageErrors.length||r.consoleErrors.length)throw Error(`Unresolved ${name} browser failure.`);
 suites[name]={passed:r.passed,failed:r.failed,seconds:r.seconds};
}
const tap=await read('artifacts/node-tests.txt'),total=Number(tap.match(/^# tests (\d+)/m)?.[1]),passed=Number(tap.match(/^# pass (\d+)/m)?.[1]),failed=Number(tap.match(/^# fail (\d+)/m)?.[1]);
if(!total||failed||passed!==total)throw Error('Node evidence is absent or contains failures.');
if(!tap.includes(hash))throw Error('Node verification log does not include this build hash. Run npm run verify > artifacts/node-tests.txt.');
const studio=JSON.parse(await read('artifacts/browser-studio.json')),browserTotal=Object.values(suites).reduce((a,b)=>a+b.passed,0);
const browser=spawnSync(process.env.BROWSER_EXECUTABLE||'chromium',['--version'],{encoding:'utf8'}).stdout?.trim()||'See browser test runner';
const summary={version:build.version,generatedAt:new Date().toISOString(),standaloneSHA256:hash,node:{total,passed,failed},browser:{total:browserTotal,passed:browserTotal,failed:0,suites,version:browser},environment:{node:process.version,mode:'inline standalone, explicit Storage test doubles',nativeURLNavigationVerified:false,nativeBrowserStorageVerified:false,nativeWebGLVerified:false,realMobileDevicesVerified:false,pwaVerified:false},rendererMetrics:studio.metrics};
await writeFile(new URL('artifacts/ACCEPTANCE-SUMMARY.json',root),JSON.stringify(summary,null,2)+'\n');
const m=studio.metrics,rows=Object.entries(suites).map(([k,v])=>`| 浏览器 ${k} | ${v.passed} / ${v.passed} | 无失败 |`).join('\n');
const report=`# STRATA · ATELIER 02 验收记录\n\n版本：${build.version}\n\n报告生成时间（UTC）：${summary.generatedAt}\n\n## 交付与校验\n\n自包含 HTML 的 SHA256：\n\n\`\`\`text\n${hash}\n\`\`\`\n\n所有浏览器报告都记录同一份 HTML 的哈希。汇总脚本会拒绝包含失败、脚本异常或旧构建哈希的报告。原始记录位于 artifacts/，可以重新执行测试，而不是只有一份结论说明。\n\n## 自动检查结果\n\n| 类别 | 结果 | 说明 |\n| --- | --- | --- |\n| Node | ${passed} / ${total} | 规则、存储、交付、HTTP 服务、C/WASM 内核与旧存档恢复 |\n${rows}\n\n浏览器检查合计 **${browserTotal} / ${browserTotal}**。各套件未捕获 JavaScript 异常和控制台错误均为 0。\n\n规则检查包括 24 个固定关卡，以及 200 组生成关卡的逐步合法路线回放。这些是可解参考路线验证，不代表最短解、唯一解或商业关卡难度已经经过玩家研究。\n\n新增内核测试直接调用实际 WASM 导出函数，验证三角形覆盖、遮挡、透明混合、楼层裁切、流体 UV 裁切、贴图采样、法线着色、缓冲清理和真实阴影深度，而不只是匹配源码文字。\n\n新增浏览器流程检查展示隔离、焦点约束与恢复、减少动态效果、相机取景变化、平滑镜头、主动环视、即时画质切换、剖层隐藏、PNG 导出、反复换关、最大 7×5×7 工坊、无 WASM 降级、手机展示和双指缩放。旧版实际导出的合成测试存档也经过文件上传、恢复和继续布管。\n\n## 测试环境与边界\n\n浏览器：${browser}\n\nNode：${process.version}\n\n本环境实际渲染后端：${m.home.backend}。WebGL 探测：${JSON.stringify(m.webglProbe)}。\n\n浏览器以 set_content 加载交付 HTML 的完整内容。没有使用替代 UI；但这种加载方式不验证 HTTP 来源、file:// 导航、PWA 缓存或浏览器原生存储。存储流程使用明确的 Storage 测试替身；另外测试了真实存储不可用时显示提示并继续游玩的路径。\n\n手机和双触点用例为 Chromium 视口与输入模拟，不是真实 iPhone、Android 或 iPad 的验收。\n\nNode 测试实际启动本地静态服务并请求主页和资源，检查 HTTP、MIME、HEAD、404、405、路径越界处理。这与浏览器能否在目标设备上打开该来源是两项不同检查。\n\n## CPU 实测样本\n\n下列数据仅属于当前容器中的 CPU 回退，不能外推为原生 GPU 帧率，也不是目标设备基准。静止状态采用按需绘制，FPS 为空并非画面故障。frameMs 是最近一次实际绘制耗时，不是多设备统计或长期均值。\n\n| 场景 | 三角形 | 画布像素 | 最近一次绘制 | 策略 |\n| --- | --- | --- | --- | --- |\n| 主页 | ${m.home.triangles.toLocaleString('en')} | ${m.home.canvas.width} × ${m.home.canvas.height} | ${m.home.frameMs} ms | 清晰静帧，按变化绘制 |\n| 第 24 关参考路线 | ${m.finalLevel.triangles.toLocaleString('en')} | ${m.finalLevel.canvas.width} × ${m.finalLevel.canvas.height} | ${m.finalLevel.frameMs} ms | 清晰静帧，按变化绘制 |\n| 主动环视 | ${m.cpuOrbit.triangles.toLocaleString('en')} | ${m.cpuOrbit.canvas.width} × ${m.cpuOrbit.canvas.height} | ${m.cpuOrbit.frameMs} ms；采样约 ${m.cpuOrbit.fps} FPS | 动态像素预算 |\n| 最大工坊空管状态 | ${m.maxWorkshop.triangles.toLocaleString('en')} | ${m.maxWorkshop.canvas.width} × ${m.maxWorkshop.canvas.height} | ${m.maxWorkshop.frameMs} ms | 按变化绘制 |\n\n重复换关后回到同一第 24 关，活动几何与纹理计数保持一致：${m.repeatSceneCounts.before.geometries} → ${m.repeatSceneCounts.after.geometries} 个几何，${m.repeatSceneCounts.before.textures} → ${m.repeatSceneCounts.after.textures} 个纹理。这个检查不等同于实际 GPU 的长期内存泄漏测试。\n\n## 画面证据\n\nartifacts/11-atelier-home.png：新版主页。\n\nartifacts/12-atelier-presentation.png：实际装置展示。\n\nartifacts/13-atelier-detail.png：实际细节镜头。\n\nartifacts/14-atelier-final-level.png：第 24 关合法参考路线回放后的画面。\n\nartifacts/15-exported-poster.png：由程序截图按钮实际下载的 PNG。\n\nartifacts/16-atelier-mobile-home.png 与 17-atelier-mobile-play.png：手机视口。\n\n另外包括正面、俯视、剖层、关卡图鉴、工坊、平板及早期观察帧。全部都是交付程序运行截图，不是生成式宣传图。\n\n## 尚未完成的发布验收\n\n原生 WebGL 材质、GPU 着色器编译与链接、PMREM/透射/后处理实际表现和帧率；真实手机及 Safari；浏览器来源与直接 HTML 打开；原生存储和长期恢复；PWA 安装与缓存升级；20 分钟以上的目标 GPU 稳定性；正式关卡难度试玩。\n\n未接入支付、广告、账号、云存档、排行榜和渠道 SDK。本版本仍为交付候选版，不是已经完成渠道审核或全平台验证的商业发行版。更多发布项见 RELEASE_CHECKLIST.md。\n`;
await writeFile(new URL('docs/QA_REPORT.md',root),report);
console.log(`Acceptance evidence verified: ${passed} Node + ${browserTotal} browser checks. SHA256 ${hash}`);
